#ifndef __dlgAbout__
#define __dlgAbout__

/**
@file
Subclass of dlgAbout, which is generated by wxFormBuilder.
*/

#include "gui.h"

namespace P3D
{

	/** Implementing dlgAbout */
	class dlgAbout : public dlgAboutGui
	{
	protected:
		// Handlers for dlgAbout events.
		void OnClose( wxCommandEvent& event );
		
	public:
		/** Constructor */
		dlgAbout( wxWindow* parent );
	};

}

#endif // __dlgAbout__
