#ifndef __panDataTool__
#define __panDataTool__

/**
@file
Subclass of panDataTool, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing panDataTool */
class panDataTool : public panDataToolGui
{
protected:
	// Handlers for panDataTool events.
	void toolCreateFolderClicked( wxCommandEvent& event );
	void toolImportClicked( wxCommandEvent& event );
	void toolDeleteClicked( wxCommandEvent& event );
	void toolPreviewClicked( wxCommandEvent& event );
	void toolListSizeClicked( wxCommandEvent& event );
	void panListLeftDClick( wxMouseEvent& event );
	void panListLeftDown( wxMouseEvent& event );
	
public:
	/** Constructor */
	panDataTool( wxWindow* parent );
};

#endif // __panDataTool__
