#ifndef __panRollup__
#define __panRollup__

/**
@file
Subclass of panRollupGui, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing panRollupGui */
class panRollup : public panRollupGui
{
protected:
	// Handlers for panRollupGui events.
	void btnEntityToggled( wxCommandEvent& event );
	void btnSolidToggled( wxCommandEvent& event );
	void btnAreaToggled( wxCommandEvent& event );
	void btnTerrainToggled( wxCommandEvent& event );
	void tabCreateEntitiesDblClick( wxListEvent& event );
	void txtFilterOnText( wxCommandEvent& event );
	void txtFilterOnEnter( wxCommandEvent& event );
	void btnCreateEntityClicked( wxCommandEvent& event );
	void btnPickClicked( wxCommandEvent& event );
	void tabEventsParamLeaveFocus( wxFocusEvent& event );
	void tabEventsParamEnterFocus( wxFocusEvent& event );
	void btnAddEventClicked( wxCommandEvent& event );
	void btnCopyEventClicked( wxCommandEvent& event );
	void btnPasteEventClicked( wxCommandEvent& event );
	void tabEventsDeletePressed( wxCommandEvent& event );
	void tabGroupsSelectedOnCombo( wxCommandEvent& event );
	void tabGroupsSelectedOnKeyUp( wxKeyEvent& event );
	void tabGroupsSelectedOnText( wxCommandEvent& event );
	void tabGroupsSelectedOnEnterCreate( wxCommandEvent& event );
	void tabGroupsCreateNewPressed( wxCommandEvent& event );
	void tabGroupsDeletePressed( wxCommandEvent& event );
	void tabGroupsAddSelectionToGroupPressed( wxCommandEvent& event );
	void tabGroupsSelectAllPressed( wxCommandEvent& event );
	void tabGroupsListDblClick( wxCommandEvent& event );
	void tabGroupsMakeSelectionFromHighlightedPressed( wxCommandEvent& event );
	void tabGroupsRemoveHighlightedPressed( wxCommandEvent& event );
	void tabGroupsClearListPressed( wxCommandEvent& event );
	
public:
	/** Constructor */
	panRollup( wxWindow* parent );
};

#endif // __panRollup__
