/* Panther3D Engine © 2004-2008 Reversity Studios (www.reversity.org)
* This contents may be used and/or copied only with the written permission or
* terms and conditions stipulated in agreement/contract.
-----------------------------------------------------------------------------
Authors: kex1k, am!go
*/

struct psout
{
  float4 color : COLOR;
};

psout main(float4 color : COLOR)
{
  psout OUT;
  OUT.color = color;
  return OUT;
}

